name: Run my python
on: 
  push: # do this every push
  schedule:
  - cron: "30 22 * * *"
jobs: 
  build:
    name: set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # what kind of github action version to use
    - name: Run my python
      run: python3 Test1.py
